class Config:
    # Window settings
    WIDTH = 800
    HEIGHT = 800
    FONT_NAME = 'roboto'
    FONT_SIZE = 24

    # World settings
    GRID_COUNT = 80
    FOOD_GEN_COUNT = 200
    MAX_FOOD = 10
    TERRAIN_GEN_COUNT = 400
    MAX_TERRAIN = 2

    # Agent settings
    INITIAL_AGENT_COUNT = 100
    AGENT_SIZE = 7
    AGENT_SPEED = 0.4
    AGENT_FOOD_DECAY_MIN = 0.0
    AGENT_FOOD_DECAY_MAX = 0.15
    AGENT_POOP_PROB = 0.98
    AGENT_POOP_AMOUNT_MIN = 0.0
    AGENT_POOP_AMOUNT_MAX = 0.1
    AGENT_REPRODUCE_FOOD_THRESHOLD = 10
    AGENT_REPRODUCE_FOOD_COST = 5
    AGENT_REPRODUCE_NEW_FOOD = 3
    AGENT_EAT_THRESHOLD = 2
    AGENT_EAT_AMOUNT = 1
    AGENT_DEATH_AGE = 5000
    AGENT_DEATH_PROB = 0.001